### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [yanna1986/about#1]
1)
проверьте отступы
![image](https://user-images.githubusercontent.com/8464662/90480692-4974d380-e139-11ea-89f3-fa1b4262f848.png)
![image](https://user-images.githubusercontent.com/8464662/90481064-d029b080-e139-11ea-9f6f-6b2042a75a0d.png)

2)
невалидный css
![image](https://user-images.githubusercontent.com/8464662/90480821-7cb76280-e139-11ea-85b5-2883ffd324fb.png)

3)
ограничение контента не работает
![image](https://user-images.githubusercontent.com/8464662/90480883-948ee680-e139-11ea-9693-4fd58cd86b1a.png)
![image](https://user-images.githubusercontent.com/8464662/90480935-a6708980-e139-11ea-972f-15084cf40beb.png)

4)
размер шрифта под различные разрешение некорректен
![image](https://user-images.githubusercontent.com/8464662/90480979-b7b99600-e139-11ea-82e6-24152b5224e5.png)

5)
размеры некорректны
![image](https://user-images.githubusercontent.com/8464662/90481087-d9b31880-e139-11ea-91ca-d69b9d016733.png)

**Comment by yanna1986** [comment]
Андрей, я исправляю и заново высылаю Вам страницу и ссылку уже с
исправлениями?

вт, 18 авг. 2020 г. в 10:02, Andrey <notifications@github.com>:

**Comment by Alecto** [comment]
Да. Повторно сбросьте те-же ссылки, у меня их не будет.

Вт, 18 серп. 2020, 10:50 користувач yanna1986 <notifications@github.com>
пише:

**Comment by yanna1986** [comment]
Андрей, Добрый день! Я могу Вам выслать исправления частями? У меня ноут
забрали в ремонт жесткий диск лег. Я успела вчера сделать только 3
исправления и закоммитить. Сегодня постараюсь забрать рабочий ноут домой,
чтоб остальное переделать.

вт, 18 авг. 2020 г. в 11:32, Andrey <notifications@github.com>:

**Comment by Alecto** [comment]
лучше все исправления сразу и по ним уже будем двигаться дальше.

ср, 19 серп. 2020 о 16:11 yanna1986 <notifications@github.com> пише:

**Comment by yanna1986** [comment]
Доброе утро!
Ночью, все переустановила.
https://github.com/yanna1986/about
https://yanna1986.github.io/about/

чт, 20 авг. 2020 г. в 06:56, Andrey <notifications@github.com>:

**Comment by Alecto** [comment]
6)
неправильные размеры кнопок под различные разрешения
![image](https://user-images.githubusercontent.com/8464662/90759364-fb9ecd80-e2e8-11ea-82ae-780e3eeb7dcf.png)

7)
неправильный размер
![image](https://user-images.githubusercontent.com/8464662/90759503-2f79f300-e2e9-11ea-984c-0c95a01d5420.png)
![image](https://user-images.githubusercontent.com/8464662/90759560-40c2ff80-e2e9-11ea-9153-dd593e1b2959.png)

**Comment by yanna1986** [comment]
https://github.com/yanna1986/about
  https://yanna1986.github.io/about/
добрый вечер

чт, 20 авг. 2020 г. в 13:31, Andrey <notifications@github.com>:

**Comment by Alecto** [comment]
8)
требования к минимальной высоте блоков не выполнены
![image](https://user-images.githubusercontent.com/8464662/90857547-07dc6680-e38d-11ea-9d95-3647339efd15.png)

**Comment by yanna1986** [comment]
[image: image.png]
[image: image.png]

Андрей, добрый день! Я высоту не меняла, когда было верстка с Вами я
оставила те же данные. В чем ошибка, я просто не понимаю.

пт, 21 авг. 2020 г. в 09:03, Andrey <notifications@github.com>:

**Comment by Alecto** [comment]
Я не доделал, это ваша работа. Посмотрите требования в макете, или
мастер-шаблон

Пт, 21 серп. 2020, 09:54 користувач yanna1986 <notifications@github.com>
пише:

**Comment by yanna1986** [comment]
Андрей, согласно шаблона  https://alecto.github.io/grid-template/
Используются 2 медиа запроса, которые отличают мою работу от шаблона. Я
данные запросы не нашла в библиотеки по медиа, которую вы нам давали при
верстке.
А именно @media (min-height:691px){
.skill-item{
min-height:calc(33.33vh-20px*0.66);
}
}
@media(max-height:690px){
.skill-item{
min-height:calc(230px-20px*0.66);
}
}
Это я нашла как отличии  между своей работой и шаблоном.  Если в этом
ошибка мне его нужно отдельно добавить в миксины для получения необходимого
размера блоков?

Андрей, я прошу прощение за может быть настырность со своей стороны, я
просто хочу разобраться.


пт, 21 авг. 2020 г. в 10:04, Andrey <notifications@github.com>:

**Comment by Alecto** [comment]
медиамиксины нужны для повторного использования.
указанный код повторно не используется, это частный случай, так что - как с
миксинами не обязательно.

но, код учитывает минимальную высоту, или его реализация, или ваш вариант-
обязательны.

пт, 21 серп. 2020 о 12:03 yanna1986 <notifications@github.com> пише:

**Comment by yanna1986** [comment]
https://github.com/yanna1986/about
 https://yanna1986.github.io/about/
Добрый день!


сб, 22 авг. 2020 г. в 07:37, Andrey <notifications@github.com>:

**Comment by Alecto** [comment]
8 - не исправлено

**Comment by yanna1986** [comment]
https://github.com/yanna1986/about
 https://yanna1986.github.io/about/
Добрый вечер!

пн, 24 авг. 2020 г. в 13:29, Andrey <notifications@github.com>:

**Comment by Alecto** [comment]
да, теперь правильно.
работа принята

вт, 25 серп. 2020 о 20:21 yanna1986 <notifications@github.com> пише:
